[package]
name = "selenium"
version = "0.1.0"
edition = "2021"

[dependencies]
bon = "3.3.0"
minreq = { version = "2.13.0", features = ["serde_json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
