name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: selenium
          fetch-depth: 0
          repository: SeleniumHQ/selenium
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83.0
      - name: Ready Firefox
        run: |
          sudo apt update -y && sudo apt install firefox firefox-locale-zh-hans fonts-wqy-zenhei  && wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz && tar -zxf geckodriver-v0.35.0-linux64.tar.gz
          chmod +x geckodriver
      - name: Test Firefox
        env:
          HEADLESS: true
        run: |
          cargo test
      - name: Ready Chrome
        id: chrome
        run: |
          cd selenium/rust
          sudo apt update -y 
          sudo apt install -y libgtk-3-dev
          cargo run -- --browser chrome --output json
          BROWSER_DRIVER=$(cargo run -- --browser chrome --output json | jq --raw-output '.result.driver_path')
          BROWSER_BINARY=$(cargo run -- --browser chrome --output json | jq --raw-output '.result.browser_path')
          echo $BROWSER_DRIVER
          echo $BROWSER_BINARY
          echo "BROWSER_DRIVER=$BROWSER_DRIVER" >> $GITHUB_OUTPUT
          echo "BROWSER_BINARY=$BROWSER_BINARY" >> $GITHUB_OUTPUT

      - name: Test Chrome
        env:
          BROWSER: chrome
          HEADLESS: true
          BROWSER_BINARY: ${{ steps.chrome.outputs.BROWSER_BINARY }}
          BROWSER_DRIVER: ${{ steps.chrome.outputs.BROWSER_DRIVER }}
          RUST_TEST_THREADS: 1
        run: |
          cargo test