name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83.0
      - name: Ready Firefox
        run: |
          sudo apt update -y && sudo apt install firefox firefox-locale-zh-hans fonts-wqy-zenhei  && wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz && tar -zxf geckodriver-v0.35.0-linux64.tar.gz
          chmod +x geckodriver
          nohup ./geckodriver --port=4892  > gec.log 2>&1 &
      - name: Test
        env:
          HEADLESS: true
        run: |
          cargo test || cat gec.log